# Generated by Django 5.0.7 on 2024-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
